debuglevel=info
alias=RoboSats-Arb
color=#4126a7
maxpendingchannels=6
bitcoin.active=1
bitcoin.testnet=1
bitcoin.node=bitcoind
bitcoind.rpcuser=robodev
bitcoind.rpcpass=robodev
bitcoind.rpchost=172.16.1.4:18332
bitcoind.zmqpubrawblock=tcp://172.16.1.4:18501
bitcoind.zmqpubrawtx=tcp://172.16.1.4:18502
tor.active=0
listen=localhost:9735
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
tlsextraip=0.0.0.0
