#!/usr/bin/env python3
"""Materialize /Agentic/.env and Claude local env from canonical Bybit/GhostCLI files."""

from __future__ import annotations

import json
from pathlib import Path

from env import BYBIT_ENV, LOCAL_ENV, apply, parse_env_file

ROOT = Path(__file__).resolve().parent.parent
SETTINGS_LOCAL = ROOT / ".claude" / "settings.local.json"


def main() -> None:
    status = apply()
    bybit = parse_env_file(BYBIT_ENV)
    key = bybit.get("BYBIT_REAL_API_KEY") or ""
    secret = bybit.get("BYBIT_REAL_API_SECRET") or ""
    if not key or not secret:
        raise SystemExit("canonical Bybit env is missing KEY/SECRET")

    lines = [
        "# Generated by internal/sync-env.py — do not commit.",
        "# Source of truth: /root/.automaton/bybit-murre.env",
        f"BYBIT_ENV_FILE={BYBIT_ENV}",
        f"BYBIT_REAL_API_KEY={key}",
        f"BYBIT_REAL_API_SECRET={secret}",
        f"BYBIT_API_KEY={key}",
        f"BYBIT_API_SECRET={secret}",
        "BYBIT_MODE=live",
        "BYBIT_CATEGORY=spot",
    ]
    LOCAL_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    LOCAL_ENV.chmod(0o600)

    SETTINGS_LOCAL.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "env": {
            "BYBIT_ENV_FILE": str(BYBIT_ENV),
            "BYBIT_REAL_API_KEY": key,
            "BYBIT_REAL_API_SECRET": secret,
            "BYBIT_API_KEY": key,
            "BYBIT_API_SECRET": secret,
            "BYBIT_MODE": "live",
            "BYBIT_CATEGORY": "spot",
        }
    }
    SETTINGS_LOCAL.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    SETTINGS_LOCAL.chmod(0o600)

    print(
        "synced internal env:",
        f"bybit_key={status['bybit_key']}",
        f"bybit_secret={status['bybit_secret']}",
        f"mode={status['mode']}",
        flush=True,
    )


if __name__ == "__main__":
    main()
